#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="${REPO_DIR:-/mnt/c/Users/ellis/Documents/VS Code/CFWrinklePINN}"
VENV_PATH="${VENV_PATH:-/home/ellis/venvs/cfwrinkle}"
SESSION_NAME="${SESSION_NAME:-level4_finalexec}"
LOG_PATH="${LOG_PATH:-/home/ellis/cfwrinkle/logs/level4_finalexec.log}"

# Proven profile defaults.
AUTO_RESUME="${AUTO_RESUME:-1}"
FINE_FEATURE_NORMALIZE="${FINE_FEATURE_NORMALIZE:-1}"
EPOCHS="${EPOCHS:-50}"
HIDDEN_DIM="${HIDDEN_DIM:-64}"
MAX_TIMESTEPS="${MAX_TIMESTEPS:-96}"
ATTN_BATCH_NODES="${ATTN_BATCH_NODES:-64}"
DECODER_CHUNK_T="${DECODER_CHUNK_T:-12}"
AMP_DTYPE="${AMP_DTYPE:-bfloat16}"
CFWRINKLE_PHYSICS_WARMUP_EPOCHS="${CFWRINKLE_PHYSICS_WARMUP_EPOCHS:-5}"
CFWRINKLE_PHYSICS_RAMP_EPOCHS="${CFWRINKLE_PHYSICS_RAMP_EPOCHS:-15}"
CFWRINKLE_FINE_ELEM_REGIONS="${CFWRINKLE_FINE_ELEM_REGIONS:-4}"
CFWRINKLE_FINE_LOSS_CHUNK_ELEMS="${CFWRINKLE_FINE_LOSS_CHUNK_ELEMS:-2048}"
CFWRINKLE_AUX_LOSS_INTERVAL="${CFWRINKLE_AUX_LOSS_INTERVAL:-1}"
CFWRINKLE_DISABLE_FINE_COHERENCE="${CFWRINKLE_DISABLE_FINE_COHERENCE:-0}"
CFWRINKLE_DISABLE_FINE_COUPLING="${CFWRINKLE_DISABLE_FINE_COUPLING:-0}"
CFWRINKLE_DISABLE_FINE_BUCKLING="${CFWRINKLE_DISABLE_FINE_BUCKLING:-0}"
CFWRINKLE_DISABLE_FINE_DZ_MONO="${CFWRINKLE_DISABLE_FINE_DZ_MONO:-0}"
PYTORCH_HIP_ALLOC_CONF="${PYTORCH_HIP_ALLOC_CONF:-garbage_collection_threshold:0.5,max_split_size_mb:512,roundup_power2_divisions:8}"

if pgrep -f "python -u -m training.train --model-type cross-scale --all-folds" >/dev/null 2>&1; then
  echo "Track B Level 4 trainer is already running; not launching a duplicate."
  exit 0
fi

tmux kill-session -t "$SESSION_NAME" 2>/dev/null || true
tmux new-session -d -s "$SESSION_NAME" \
  "cd \"$REPO_DIR\" && \
   source \"$VENV_PATH/bin/activate\" && \
   export LD_PRELOAD=/opt/rocm-7.2.0/lib/libamdhip64.so && \
   export PYTHONUNBUFFERED=1 && \
   export AUTO_RESUME=\"$AUTO_RESUME\" FINE_FEATURE_NORMALIZE=\"$FINE_FEATURE_NORMALIZE\" && \
   export EPOCHS=\"$EPOCHS\" HIDDEN_DIM=\"$HIDDEN_DIM\" MAX_TIMESTEPS=\"$MAX_TIMESTEPS\" && \
   export ATTN_BATCH_NODES=\"$ATTN_BATCH_NODES\" DECODER_CHUNK_T=\"$DECODER_CHUNK_T\" AMP_DTYPE=\"$AMP_DTYPE\" && \
   export CFWRINKLE_PHYSICS_WARMUP_EPOCHS=\"$CFWRINKLE_PHYSICS_WARMUP_EPOCHS\" CFWRINKLE_PHYSICS_RAMP_EPOCHS=\"$CFWRINKLE_PHYSICS_RAMP_EPOCHS\" && \
   export CFWRINKLE_FINE_ELEM_REGIONS=\"$CFWRINKLE_FINE_ELEM_REGIONS\" CFWRINKLE_FINE_LOSS_CHUNK_ELEMS=\"$CFWRINKLE_FINE_LOSS_CHUNK_ELEMS\" && \
   export CFWRINKLE_AUX_LOSS_INTERVAL=\"$CFWRINKLE_AUX_LOSS_INTERVAL\" && \
   export CFWRINKLE_DISABLE_FINE_COHERENCE=\"$CFWRINKLE_DISABLE_FINE_COHERENCE\" CFWRINKLE_DISABLE_FINE_COUPLING=\"$CFWRINKLE_DISABLE_FINE_COUPLING\" && \
   export CFWRINKLE_DISABLE_FINE_BUCKLING=\"$CFWRINKLE_DISABLE_FINE_BUCKLING\" CFWRINKLE_DISABLE_FINE_DZ_MONO=\"$CFWRINKLE_DISABLE_FINE_DZ_MONO\" && \
   export PYTORCH_HIP_ALLOC_CONF=\"$PYTORCH_HIP_ALLOC_CONF\" && \
   bash run_cross_scale_level4.sh 2>&1 | tee \"$LOG_PATH\""

echo "Resumed in tmux session: $SESSION_NAME"
echo "Attach: tmux attach -t $SESSION_NAME"
