#!/usr/bin/env bash
# Resume Track C Level 4 training in a detached tmux session.
# Track B reference preserved at: cross_scale_level4_cv/
set -euo pipefail

REPO_DIR="${REPO_DIR:-/mnt/c/Users/ellis/Documents/VS Code/CFWrinklePINN}"
VENV_PATH="${VENV_PATH:-/home/ellis/venvs/cfwrinkle}"
SESSION_NAME="${SESSION_NAME:-level4_trackc}"
LOG_PATH="${LOG_PATH:-/home/ellis/cfwrinkle/logs/level4_trackc.log}"

# Track C defaults — all ROCm hard constraints baked in
AUTO_RESUME="${AUTO_RESUME:-1}"
FINE_FEATURE_NORMALIZE="${FINE_FEATURE_NORMALIZE:-1}"
USE_FINE_MP="${USE_FINE_MP:-1}"
USE_TORCH_COMPILE="${USE_TORCH_COMPILE:-1}"
TORCH_ROCM_FA_PREFER_CK="${TORCH_ROCM_FA_PREFER_CK:-0}"  # CK=Wave64 misfires on gfx1100 Wave32 with torch.compile
EPOCHS="${EPOCHS:-50}"
HIDDEN_DIM="${HIDDEN_DIM:-64}"
MAX_TIMESTEPS="${MAX_TIMESTEPS:-96}"
ATTN_BATCH_NODES="${ATTN_BATCH_NODES:-512}"   # 512 fills GPU kernels (RDNA3 native); 64 underutilises
DECODER_CHUNK_T="${DECODER_CHUNK_T:-6}"
AMP_DTYPE="${AMP_DTYPE:-float16}"             # RDNA3 gfx1100 native fp16 (bfloat16 slower on this arch)
CFWRINKLE_FINE_DZ_WEIGHT="${CFWRINKLE_FINE_DZ_WEIGHT:-4.0}"
CFWRINKLE_PHYSICS_WARMUP_EPOCHS="${CFWRINKLE_PHYSICS_WARMUP_EPOCHS:-5}"
CFWRINKLE_PHYSICS_RAMP_EPOCHS="${CFWRINKLE_PHYSICS_RAMP_EPOCHS:-15}"
CFWRINKLE_FINE_ELEM_REGIONS="${CFWRINKLE_FINE_ELEM_REGIONS:-4}"
CFWRINKLE_FINE_LOSS_CHUNK_ELEMS="${CFWRINKLE_FINE_LOSS_CHUNK_ELEMS:-512}"
CFWRINKLE_AUX_LOSS_INTERVAL="${CFWRINKLE_AUX_LOSS_INTERVAL:-1}"
CFWRINKLE_DISABLE_FINE_COHERENCE="${CFWRINKLE_DISABLE_FINE_COHERENCE:-0}"
CFWRINKLE_DISABLE_FINE_COUPLING="${CFWRINKLE_DISABLE_FINE_COUPLING:-0}"
CFWRINKLE_DISABLE_FINE_BUCKLING="${CFWRINKLE_DISABLE_FINE_BUCKLING:-0}"
CFWRINKLE_DISABLE_FINE_DZ_MONO="${CFWRINKLE_DISABLE_FINE_DZ_MONO:-0}"
PYTORCH_HIP_ALLOC_CONF="${PYTORCH_HIP_ALLOC_CONF:-expandable_segments:True,max_split_size_mb:128,garbage_collection_threshold:0.8}"

if pgrep -f "python -u -m training.train --model-type cross-scale --all-folds" >/dev/null 2>&1; then
  echo "A cross-scale trainer is already running; not launching a duplicate."
  exit 0
fi

tmux kill-session -t "$SESSION_NAME" 2>/dev/null || true
tmux new-session -d -s "$SESSION_NAME" \
  "cd \"$REPO_DIR\" && \
   source \"$VENV_PATH/bin/activate\" && \
   export LD_PRELOAD=/opt/rocm-7.2.0/lib/libamdhip64.so && \
   export PYTHONUNBUFFERED=1 && \
   export AUTO_RESUME=\"$AUTO_RESUME\" FINE_FEATURE_NORMALIZE=\"$FINE_FEATURE_NORMALIZE\" && \
   export USE_FINE_MP=\"$USE_FINE_MP\" USE_TORCH_COMPILE=\"$USE_TORCH_COMPILE\" && \
   export TORCH_ROCM_FA_PREFER_CK=\"$TORCH_ROCM_FA_PREFER_CK\" && \
   export TORCHINDUCTOR_MAX_AUTOTUNE=1 && \
   export EPOCHS=\"$EPOCHS\" HIDDEN_DIM=\"$HIDDEN_DIM\" MAX_TIMESTEPS=\"$MAX_TIMESTEPS\" && \
   export ATTN_BATCH_NODES=\"$ATTN_BATCH_NODES\" DECODER_CHUNK_T=\"$DECODER_CHUNK_T\" AMP_DTYPE=\"$AMP_DTYPE\" && \
   export CFWRINKLE_FINE_DZ_WEIGHT=\"$CFWRINKLE_FINE_DZ_WEIGHT\" && \
   export CFWRINKLE_PHYSICS_WARMUP_EPOCHS=\"$CFWRINKLE_PHYSICS_WARMUP_EPOCHS\" CFWRINKLE_PHYSICS_RAMP_EPOCHS=\"$CFWRINKLE_PHYSICS_RAMP_EPOCHS\" && \
   export CFWRINKLE_FINE_ELEM_REGIONS=\"$CFWRINKLE_FINE_ELEM_REGIONS\" CFWRINKLE_FINE_LOSS_CHUNK_ELEMS=\"$CFWRINKLE_FINE_LOSS_CHUNK_ELEMS\" && \
   export CFWRINKLE_AUX_LOSS_INTERVAL=\"$CFWRINKLE_AUX_LOSS_INTERVAL\" && \
   export CFWRINKLE_DISABLE_FINE_COHERENCE=\"$CFWRINKLE_DISABLE_FINE_COHERENCE\" CFWRINKLE_DISABLE_FINE_COUPLING=\"$CFWRINKLE_DISABLE_FINE_COUPLING\" && \
   export CFWRINKLE_DISABLE_FINE_BUCKLING=\"$CFWRINKLE_DISABLE_FINE_BUCKLING\" CFWRINKLE_DISABLE_FINE_DZ_MONO=\"$CFWRINKLE_DISABLE_FINE_DZ_MONO\" && \
   export PYTORCH_HIP_ALLOC_CONF=\"$PYTORCH_HIP_ALLOC_CONF\" && \
   bash run_cross_scale_level4_trackc.sh 2>&1 | tee \"$LOG_PATH\""

echo "Track C resumed in tmux session: $SESSION_NAME"
echo "Attach: tmux attach -t $SESSION_NAME"
echo "Log:    $LOG_PATH"
