#!/usr/bin/env bash
# Resume Track C CUDA training in a detached tmux session (RunPod bare-metal Linux).
# Target: RTX Pro 6000 Blackwell (96 GB GDDR7). DO NOT use on ROCm/AMD.
set -euo pipefail

REPO_DIR="${REPO_DIR:-/workspace/repo}"
VENV_PATH="${VENV_PATH:-/workspace/venv}"
SESSION_NAME="${SESSION_NAME:-level4_trackc_cuda}"
LOG_PATH="${LOG_PATH:-/workspace/logs/level4_trackc_cuda.log}"
DATA_DIR="${DATA_DIR:-/workspace/data}"
CHECKPOINT_DIR="${CHECKPOINT_DIR:-/workspace/checkpoints}"

# Blackwell defaults
AUTO_RESUME="${AUTO_RESUME:-1}"
FINE_FEATURE_NORMALIZE="${FINE_FEATURE_NORMALIZE:-1}"
USE_FINE_MP="${USE_FINE_MP:-1}"
USE_TORCH_COMPILE="${USE_TORCH_COMPILE:-1}"
TORCH_COMPILE_MODE="${TORCH_COMPILE_MODE:-max-autotune}"
EPOCHS="${EPOCHS:-50}"
HIDDEN_DIM="${HIDDEN_DIM:-96}"
MAX_TIMESTEPS="${MAX_TIMESTEPS:-128}"
ATTN_BATCH_NODES="${ATTN_BATCH_NODES:-1024}"
DECODER_CHUNK_T="${DECODER_CHUNK_T:-24}"
AMP_DTYPE="${AMP_DTYPE:-bfloat16}"
CFWRINKLE_FINE_DZ_WEIGHT="${CFWRINKLE_FINE_DZ_WEIGHT:-4.0}"
CFWRINKLE_PHYSICS_WARMUP_EPOCHS="${CFWRINKLE_PHYSICS_WARMUP_EPOCHS:-5}"
CFWRINKLE_PHYSICS_RAMP_EPOCHS="${CFWRINKLE_PHYSICS_RAMP_EPOCHS:-15}"
CFWRINKLE_FINE_ELEM_REGIONS="${CFWRINKLE_FINE_ELEM_REGIONS:-4}"
CFWRINKLE_FINE_LOSS_CHUNK_ELEMS="${CFWRINKLE_FINE_LOSS_CHUNK_ELEMS:-2048}"
CFWRINKLE_AUX_LOSS_INTERVAL="${CFWRINKLE_AUX_LOSS_INTERVAL:-1}"
CFWRINKLE_DISABLE_FINE_COHERENCE="${CFWRINKLE_DISABLE_FINE_COHERENCE:-0}"
CFWRINKLE_DISABLE_FINE_COUPLING="${CFWRINKLE_DISABLE_FINE_COUPLING:-0}"
CFWRINKLE_DISABLE_FINE_BUCKLING="${CFWRINKLE_DISABLE_FINE_BUCKLING:-0}"
CFWRINKLE_DISABLE_FINE_DZ_MONO="${CFWRINKLE_DISABLE_FINE_DZ_MONO:-0}"
PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True,garbage_collection_threshold:0.9}"
TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-/workspace/.triton_cache}"

if pgrep -f "python -u -m training.train --model-type cross-scale --all-folds" >/dev/null 2>&1; then
  echo "A cross-scale trainer is already running; not launching a duplicate."
  exit 0
fi

mkdir -p "$(dirname "$LOG_PATH")" "$TRITON_CACHE_DIR"
tmux kill-session -t "$SESSION_NAME" 2>/dev/null || true
tmux new-session -d -s "$SESSION_NAME" \
  "cd \"$REPO_DIR\" && \
   source \"$VENV_PATH/bin/activate\" && \
   export PYTHONUNBUFFERED=1 && \
   export AUTO_RESUME=\"$AUTO_RESUME\" FINE_FEATURE_NORMALIZE=\"$FINE_FEATURE_NORMALIZE\" && \
   export USE_FINE_MP=\"$USE_FINE_MP\" USE_TORCH_COMPILE=\"$USE_TORCH_COMPILE\" && \
   export TORCH_COMPILE_MODE=\"$TORCH_COMPILE_MODE\" && \
   export TORCHINDUCTOR_MAX_AUTOTUNE=1 && \
   export TRITON_CACHE_DIR=\"$TRITON_CACHE_DIR\" && \
   export EPOCHS=\"$EPOCHS\" HIDDEN_DIM=\"$HIDDEN_DIM\" MAX_TIMESTEPS=\"$MAX_TIMESTEPS\" && \
   export ATTN_BATCH_NODES=\"$ATTN_BATCH_NODES\" DECODER_CHUNK_T=\"$DECODER_CHUNK_T\" AMP_DTYPE=\"$AMP_DTYPE\" && \
   export CFWRINKLE_FINE_DZ_WEIGHT=\"$CFWRINKLE_FINE_DZ_WEIGHT\" && \
   export CFWRINKLE_PHYSICS_WARMUP_EPOCHS=\"$CFWRINKLE_PHYSICS_WARMUP_EPOCHS\" CFWRINKLE_PHYSICS_RAMP_EPOCHS=\"$CFWRINKLE_PHYSICS_RAMP_EPOCHS\" && \
   export CFWRINKLE_FINE_ELEM_REGIONS=\"$CFWRINKLE_FINE_ELEM_REGIONS\" CFWRINKLE_FINE_LOSS_CHUNK_ELEMS=\"$CFWRINKLE_FINE_LOSS_CHUNK_ELEMS\" && \
   export CFWRINKLE_AUX_LOSS_INTERVAL=\"$CFWRINKLE_AUX_LOSS_INTERVAL\" && \
   export CFWRINKLE_DISABLE_FINE_COHERENCE=\"$CFWRINKLE_DISABLE_FINE_COHERENCE\" CFWRINKLE_DISABLE_FINE_COUPLING=\"$CFWRINKLE_DISABLE_FINE_COUPLING\" && \
   export CFWRINKLE_DISABLE_FINE_BUCKLING=\"$CFWRINKLE_DISABLE_FINE_BUCKLING\" CFWRINKLE_DISABLE_FINE_DZ_MONO=\"$CFWRINKLE_DISABLE_FINE_DZ_MONO\" && \
   export PYTORCH_CUDA_ALLOC_CONF=\"$PYTORCH_CUDA_ALLOC_CONF\" && \
   export DATA_DIR=\"$DATA_DIR\" CHECKPOINT_DIR=\"$CHECKPOINT_DIR\" && \
   bash run_cross_scale_level4_cuda.sh 2>&1 | tee \"$LOG_PATH\""

echo "Track C CUDA resumed in tmux session: $SESSION_NAME"
echo "Attach: tmux attach -t $SESSION_NAME"
echo "Log:    $LOG_PATH"
